### ISSUE TITLE
Confirmation Dialog 

### ISSUE THREAD

**Issue by CaiqueR** [assisrafael/react-bootstrap-utils#13] opened 2020-04-28 12:41 UTC
When I use the Confirmation Dialog component and click on procced and redirect to another screen, the scroll doesn't work anymore, it looks like an overflow:hidden has been applied
![Scroll](https://user-images.githubusercontent.com/42003129/80488281-79069280-8934-11ea-88dd-2b527f38e941.gif)

**Comment by assisrafael** [comment] 2020-04-28 12:54
Duplicate of #10

**Closed by assisrafael** 2020-04-28 12:54 UTC
